# Generated by Django 6.0 on 2025-12-27 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_department_user_company_and_more'),
        ('core', '0002_equipment_equipmentcategory_workcenter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_teams', to='accounts.company')),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'technician'}, related_name='maintenance_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
